- CHANGELOG.md
- src/picologging/__init__.py
- tests/test_logger.py
> Fix root logger instantiation with wrong arguments

- CHANGELOG.md
- src/picologging/__init__.py
- tests/test_picologging.py
> Fix getlevelname missing from module

- src/picologging/handlers.py
- src/picologging/handlers.pyi
- tests/unit/test_filehandler.py
https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler
> Add RotatingFileHandler

- src/picologging/handlers.py
- tests/unit/test_filehandler.py
- tests/unit/test_picologging.py
This should be reviewed after #33
> Uplift test coverage

- CHANGELOG.md
- benchmarks/bench_handlers.py
- src/picologging/handlers.py
- src/picologging/handlers.pyi
- tests/unit/test_buffering_handler.py
Add `MemoryHandler` from CPython https://github.com/python/cpython/blob/3f2dd0a7c0b1a5112f2164dce78fcfaa0c4b39c7/Lib/logging/handlers.py#L1333
> Add MemoryHandler

- .github/workflows/quality.yml
- benchmarks/bench_logger.py
- setup.py
- tests/fuzzing/fuzz_atheris.py
- tests/profile/profile.py
- tests/unit/test_filehandler.py
- tests/unit/test_formatter.py
- tests/unit/test_handler.py
- tests/unit/test_logger.py
- tests/unit/test_logrecord.py
- tests/unit/test_percentstyle.py
- tests/unit/test_picologging.py
- tests/unit/test_queuehandler.py
- tests/unit/test_streamhandler.py
- tests/unit/test_strformatstyle.py
- tests/unit/test_threading.py
The Python source code is already formatted, this will re-format the tests and add the Github Action check.
> Format tests

- setup.py
To reflect the project Beta status.
> Update project classifiers

- src/picologging/handler.cxx
- tests/unit/test_handler.py
> Add Handler repr

- src/picologging/config.py
- tests/unit/test_config.py
This PR brings in a recent fix to logging: https://github.com/python/cpython/pull/96530
> Make config fix

- .github/workflows/quality.yml
- src/picologging/__init__.py
> 3.7+ compatible code

- .github/workflows/hypothesis.yaml
- .github/workflows/test.yml
Updates matrices to use the legit version. Woooot.
> Test on 3.11 vs 3.11-dev

- .github/workflows/wheel.yml
- pyproject.toml
Add Windows ARM64 wheels closes https://github.com/microsoft/picologging/issues/129
> Add Windows Arm64 wheels

- pyproject.toml
> Skip testing arm64

- .github/workflows/wheel.yml
- pyproject.toml
> Compile x86 for linux and windows. Compile aarch64 for linux

- README.md
- src/picologging/_picologging.cxx
- src/picologging/logger.cxx
- src/picologging/picologging.hxx
- tests/unit/test_logger.py
> Support Logger.setLevel from string input

- tests/unit/test_formatter.py
Closes https://github.com/microsoft/picologging/issues/103
> Add tests for override formatter formatException

- src/picologging/__init__.py
- tests/unit/test_config.py
- tests/unit/test_formatter.py
- tests/unit/test_logger.py
- tests/unit/test_picologging.py
Fix formatting issues caused in the pipeline and some extra issues found by Ruff.
> Fix formatting issues

- src/picologging/__init__.py
- src/picologging/__init__.pyi
Closes https://github.com/microsoft/picologging/issues/98
This was added in Python 3.9+
Ref:
https://github.com/python/cpython/blob/f2eaa92b0cc5a37a9e6010c7c6f5ad1a230ea49b/Lib/logging/__init__.py#L1209
https://github.com/python/typeshed/blob/4c4278e80c74b10548f83236e0f56c0104bd4ed2/stdlib/logging/__init__.pyi#L828C35-L828C35
> Add FileHandler errors argument

- .github/workflows/quality.yml
- src/picologging/formatter.cxx
Closes https://github.com/microsoft/picologging/issues/117
Could also use something nicer like https://github.com/ZedThree/clang-tidy-review
> Run clang-tidy in Github actions

- .github/workflows/test.yml
- CMakeLists.txt
- src/picologging/_picologging.cxx
- src/picologging/filepathcache.cxx
- src/picologging/filepathcache.hxx
- src/picologging/logrecord.cxx
- src/picologging/logrecord.hxx
> Move filepath cache to within free-able module state

- src/picologging/formatter.cxx
- src/picologging/formatter.hxx
- src/picologging/logger.cxx
- src/picologging/logger.hxx
- src/picologging/streamhandler.cxx
> Cleanup all danging unicode references.

- src/picologging/logrecord.cxx
- tests/unit/test_logrecord.py
Closes https://github.com/microsoft/picologging/issues/123
> Allow LogRecord to be copied

- tests/unit/test_bufferinghandler.py
- tests/unit/test_config.py
- tests/unit/test_filehandler.py
- tests/unit/test_picologging.py
Closes https://github.com/microsoft/picologging/issues/170
> Fix unclosed resources in tests

- .github/workflows/test.yml
- pyproject.toml
- tests/integration/requirements.txt
- tests/integration/test_coloredlogs.py
> Verify the integration of coloredlogs is fixed

- src/picologging/compat.hxx
- src/picologging/formatstyle.cxx
- src/picologging/formatter.cxx
- src/picologging/logger.cxx
- src/picologging/logger.hxx
- tests/profile/profile.py
- Faster type checks in core path
- Implement fast calls in core logging functions
Closes #187
> [WIP] Various optimizations

- src/picologging/_picologging.cxx
- src/picologging/logrecord.cxx
- src/picologging/picologging.hxx
> Improve perf and memory usage of log records with const level names

- tests/unit/test_formatter.py
Tests the bug reported in #203
> Add a test for issue Using `asctime` in formatter
