microsoft/picologging

benchmarks/bench_handlers.py

Closes #30.
Adds benchmarks for `FileHandler`, `WatchedFileHandler` and `RotatingFileHandler`.
The `RotatingFileHandler` would perform better with larger `maxBytes` like `1MB` and more logs so it would do less IO which is closer to real-world use-case and around x3 times faster than logging but there are two points:
- It would make the benchmarks take longer
- this could apply to all other benchmarks, increasing the number of logs  will make a larger difference but I'm not sure if that's what's wanted here.

Add benchmakrs for handlers

---

.github/workflows/test.yml
CHANGELOG.md
docs/limitations.md
src/picologging/__init__.py
src/picologging/_picologging.cxx
src/picologging/formatter.cxx
src/picologging/logger.cxx
src/picologging/logger.hxx
tests/unit/test_logger.py
tests/unit/test_picologging.py

Identifies 3 bugs:
1. Exception info with `exc_info` as an instance of exception does not format correctly
2. `stack_info`/`sinfo` is not implemented correctly and doesn't add the stack trace to the log message
3. child/parent NOTSET rules are not being adhered to
```python
def test_notset_parent_level_match():
logger_child = picologging.Logger("child", picologging.NOTSET)
logger_parent = picologging.Logger("parent", picologging.DEBUG)
logger_child.parent = logger_parent
parent_io = io.StringIO()
child_io = io.StringIO()
logger_child.addHandler(picologging.StreamHandler(child_io))
logger_parent.addHandler(picologging.StreamHandler(parent_io))
logger_child.info("child message")
logger_parent.info("parent message")
parent_value = parent_io.getvalue()
child_value = child_io.getvalue()
assert …
```

Test logger edge cases

---

src/picologging/_picologging.cxx
src/picologging/picologging.hxx
tests/unit/test_picologging.py

Fixes #51  to be compatible with `logging`.
I think there's some issue with the coverage, all changes are covered but it's assuming the removed lines won't be covered.

Make getLevelName work level name arguments

---

docs/source/conf.py
src/picologging/logger.cxx
tests/unit/test_logger.py

Fixes https://github.com/microsoft/picologging/issues/56
At first I thought it should only reset lower levels, which is a bit less verbose, but it should also reset higher levels:
for example:
```py
logger.setLevel(picologging.INFO)
logger.setLevel(picologging.ERROR)
```

Fix Logger setLevel not resetting other levels

---

src/picologging/formatter.cxx
src/picologging/logger.cxx
src/picologging/streamhandler.cxx
tests/memray/profile.py

* Fixes a leak in the `asctime` field of log record
* Fixes a leak in stream writer write() and flush() calls
* Fixes a leak in stream close()

Fix loop leaks

---

src/picologging/__init__.py

Trying to work on the `dictConfig` I see `Manager` instance should be set on the root Logger because `root` is what is exposed as module variables, not manager:
https://github.com/microsoft/picologging/blob/a0aa8c610a950a53bbdd6dc78b5f163c6428bfd5/src/picologging/__init__.pyi#L338
And when accessing root the manager is None.

Set Manager on root Logger

---

src/picologging/__init__.py
tests/unit/test_logger.py

While working on the `dictConfig` I saw that the `Filter` is not exposed in `Picologging`.
Please review this before #61

Fix Filter not exported in Picologging

---

.github/workflows/quality.yml

- Upgrade Github CodeQL to V2 since V1 will be deprecated in December 2022 and receive no updates
- Fix the the pipeline failing for cpp files not found.

Upgrade Github CodeQL to V2

---

CHANGELOG.md
setup.py
src/picologging/__init__.py
src/picologging/config.py
tests/unit/test_config.py

Fixes #53 
Please review https://github.com/microsoft/picologging/pull/63 before this.

Add dictConfig

---

src/picologging/__init__.py
src/picologging/config.py
tests/unit/test_config.py

Fixes #67 .
The code was using the CPython version with PlaceHolder, it didn't have test coverage. This adds the tests and fixes the issue.

Fix dictconfig resetting child loggers

---

tests/memray/format_exception.py

The release 0.8.1 was stopped because the GH action failed: https://github.com/microsoft/picologging/actions/runs/3042080402/jobs/4899864578

Fix formatting with black

---

src/picologging/logrecord.cxx
tests/unit/test_logrecord.py

I am currently checking for differences between CPython logging module and picologging by running the CPython logging tests, and this was the first issue it found: logging.LogRecord can be a base class, picologging.LogRecord cannot. I fixed that by adding the relevant flag to tp_flags and adding a test.

Making LogRecord class derivable

---

src/picologging/handler.cxx
tests/unit/test_handler.py

The C code was previously returning the NotImplemented object, which is distinct from raising a NotImplemented error, so I changed it and added/modified a test.

Properly raise error from Handler.emit

---

src/picologging/streamhandler.cxx
tests/unit/test_streamhandler.py

StreamHandler.setStream has some very specific behavior that we weren't following. See https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler.setStream and the CPython code for reference.
This attempts to implement that behavior and adds a test for it.
I did end up removing a XDECREF on the old stream since it's now returned, not sure if that's problematic memory wise?

Properly handle return value for setStream

---

src/picologging/streamhandler.cxx
tests/unit/test_streamhandler.py

Fixes the format and allows "name" attribute to be a number.

Fixing Stream.__repr__ to match CPython

---

src/picologging/formatstyle.cxx
src/picologging/formatter.cxx
src/picologging/logrecord.hxx
tests/unit/test_logrecord.py

In https://github.com/microsoft/picologging/pull/77 subclasses of LogRecord were added, but I think these checks will prevent `handle` to accept them.
Without the change the test would fail.

Allow handle method to accept LogRecord subclasses

---

pyproject.toml

I find all the pylint warnings around docstrings distracting, and since it doesn't seem that docstrings are actually a high priority in this codebase, this config turns off the warnings. Let me know if you prefer a different approach.

Add pylint config

---

slowtests/test_logrecordhyp.py

The hypothesis filename test has failed on the last two merges to main. This PR adds the max_runs and min_passes parameters so that it will get retried 4 times and only need to pass once. If it still won't pass after 4 times, then I think we should just skip the test, so that we don't have failed tests on each merge to main.

Adding parameters to flaky decorator to increase reruns

---

.github/workflows/quality.yml
.pre-commit-config.yaml
README.md
setup.py
tests/unit/test_bufferinghandler.py
tests/unit/test_filehandler.py
tests/unit/test_sockethandler.py
tests/unit/test_streamhandler.py

As suggested in #109, this PR adds pre-commit hooks using the pre-commit package. To start off with, it has the yaml-fixer hook, the black hook, and the pyupgrade hook. I think it's nice to run pyupgrade on tests too, so I didn't exclude the tests from it, but I can exclude them if you feel otherwise.
I'll send a follow-up PR adding isort since that'll change a bunch of files.

Adding precommit with black and pyupgr

---

src/picologging/handler.cxx
src/picologging/logger.cxx
src/picologging/streamhandler.cxx

Per #116, this PR changes dealloc of Logger/Handler/StreamHandler to explicitly call the dealloc of their base type. That seems to be how it's done in CPython, from the examples I saw. And it seems to have reduced the memory leakage substantially.
memray before and after:
There seems to be one more memory leak around `self->usesTime = (FormatStyle_usesTime((FormatStyle*)self->style) == Py_True);`. It's not immediately obvious to me what the necessary change is for that one.

Call dealloc of base types

---

.devcontainer/devcontainer.json

The current devcontainer settings are marked as invalid due to vscode settings at root and not in `customizations.vscode.settings` (same for extensions).
This moves the settings to vscode settings.

moves devcontainer vscode settings

---

src/picologging/__init__.py
tests/unit/test_picologging.py

Fixes https://github.com/microsoft/picologging/issues/142

Fix `io` text_encoding on Python 3.9 and older

---

.github/workflows/test.yml
setup.py

Use latest memray

---

src/picologging/logger.cxx
src/picologging/logrecord.cxx
src/picologging/logrecord.hxx

Improve the performance of logging records by inlining log creation to remove temporary Python objects into the logger.

---

src/picologging/__init__.py
src/picologging/formatter.cxx
tests/unit/test_formatter.py

Closes https://github.com/microsoft/picologging/issues/203
Correctly format and print LogRecord.asctime field
Please merge this PR or https://github.com/microsoft/picologging/pull/209
where %f support in datefmt was also added. 
```
import time
import picologging as logging
logging.basicConfig(format="%(levelname)s - %(asctime)s - %(name)s - %(module)s - %(message)s")
logger = logging.getLogger()
logger.setLevel(logging.INFO)
if __name__ == '__main__':
for i in range(5):
time.sleep(0.4)
logger.info("Hello world! %d", i)
```
```
INFO - 2024-07-23 04:35:30,285 - root - <unknown> - Hello world! 0
INFO - 2024-07-23 04:35:30,685 - root - <unknown> - Hello world! 1
INFO - 2024-07-23 04:35:31,085 - root - <unknown> - Hello world! 2
INFO - 2024-07-23 04:35:31,485 - root - <unknown> - Hello world! …
```

Fix asctime formatting, don't print uninitialized buffer's content (issue #203)
